
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salva
 */
public class AdministrarProductos extends javax.swing.JFrame {
    private ResultSet resultado;
   private PreparedStatement enunciado;
   private Connection conexion;
    /**
     * Creates new form AdministrarProductos
     */
    public AdministrarProductos() {
        initComponents();
        conectar();
        dtm= (DefaultTableModel) tblproductos.getModel();
      dtm.setRowCount(0);
      cargarproductos();
       btnact.setEnabled(false);
       btneli.setEnabled(false);
       btncan.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ConexionBD con = new ConexionBD();
    private void conectar(){
        conexion = con.conectar();
    }    
    
     public void cargarproductos()
     {
       Object []O=new Object[5];   
        dtm.setNumRows(0);
        
        try{
           
        enunciado = conexion.prepareStatement("select * from Productos ");
        
         resultado = enunciado.executeQuery();
         while(resultado.next()){
            O[0]=resultado.getInt("idProducto");
            O[1]=resultado.getString("Nombre");
            O[2]=resultado.getFloat("Precio");
            O[3]=resultado.getFloat("PrecioDom");
            O[4]=resultado.getString("TipoProducto");            
            dtm.addRow(O);
         }
         
      }catch(Exception e){
         e.printStackTrace();
      }  
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();
        btnag = new javax.swing.JButton();
        btnact = new javax.swing.JButton();
        btneli = new javax.swing.JButton();
        btncan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtprecioDom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Id Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        txtid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 31, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtnombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 203, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtprecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 82, -1));

        tblproductos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "NOMBRE", "PRECIO LOCAL", "PRECIO A DOMICILIO", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproductos);
        if (tblproductos.getColumnModel().getColumnCount() > 0) {
            tblproductos.getColumnModel().getColumn(0).setResizable(false);
            tblproductos.getColumnModel().getColumn(1).setResizable(false);
            tblproductos.getColumnModel().getColumn(2).setResizable(false);
            tblproductos.getColumnModel().getColumn(3).setResizable(false);
            tblproductos.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 590, 403));

        btnag.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnag.setText("Agregar");
        btnag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagActionPerformed(evt);
            }
        });
        jPanel1.add(btnag, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 109, -1));

        btnact.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnact.setText("Actualizar");
        btnact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactActionPerformed(evt);
            }
        });
        jPanel1.add(btnact, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btneli.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btneli.setText("Eliminar");
        btneli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliActionPerformed(evt);
            }
        });
        jPanel1.add(btneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 109, -1));

        btncan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btncan.setText("Cancelar");
        btncan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanActionPerformed(evt);
            }
        });
        jPanel1.add(btncan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 109, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Precio local:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmbTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "B", "C" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        txtprecioDom.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtprecioDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 82, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Precio domicilio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactActionPerformed
       actualizar();
        vista2();
    }//GEN-LAST:event_btnactActionPerformed

    private void btneliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliActionPerformed
       eliminar();
        vista2(); 
    }//GEN-LAST:event_btneliActionPerformed
    public void vista2()
    {
        btnact.setEnabled(false);
        btneli.setEnabled(false);
        btnag.setEnabled(true); 
        btncan.setEnabled(false);
        txtid.setEnabled(true);
        txtid.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
        txtprecioDom.setText("");
        cargarproductos();
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      
        this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tblproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductosMouseClicked
        int r=tblproductos.getSelectedRow();
        txtid.setText(dtm.getValueAt(r, 0).toString());
        txtnombre.setText(dtm.getValueAt(r, 1).toString());
        txtprecio.setText(dtm.getValueAt(r, 2).toString());
        txtprecioDom.setText(dtm.getValueAt(r, 3).toString());
        btnact.setEnabled(true);
        btneli.setEnabled(true);
        btnag.setEnabled(false);
        btncan.setEnabled(true);
        txtid.setEnabled(false);
    }//GEN-LAST:event_tblproductosMouseClicked
    public void eliminar()
    {
        int resul;
        try{            
            enunciado = conexion.prepareStatement("delete from Productos where idProducto="+Integer.parseInt(txtid.getText())+"");        
            resul = enunciado.executeUpdate();
            if(resul > 0 ){}
            else{
                showMessageDialog(null,"Ocurrio un problema al borrar","Error",ERROR_MESSAGE);
                return;
            }
        }catch(Exception e){
            e.printStackTrace();
        }    
    }
    public void agregar()
    {        
        int resul;
        try{ 
            String id = txtid.getText();
            String idT;
            
            if(id.equals("")){
                throw new AlitasException("Ingrese el ID del producto");
            }
            if(txtnombre.getText().equals("")){
                throw new AlitasException("Ingrese el Nombre del producto");
            }
            if(txtprecio.getText().equals("")){
                throw new AlitasException("Ingrese ambos precios del producto");
            }
            if(cmbTipo.getSelectedIndex()==0){
                throw new AlitasException("Seleccione el tipo de producto");
            }
            //showMessageDialog(this,tblproductos.getRowCount());
            for (int i = 0; i<=tblproductos.getRowCount(); i++){
                idT = tblproductos.getValueAt(i, 0).toString();
                //showMessageDialog(this,idT);
                if(id.equals(idT)){                    
                    throw new AlitasException("Este ID ya ha sido registrado");                    
                }
            }
            try {
                enunciado = conexion.prepareStatement("insert into Productos(idProducto,Nombre,Precio, TipoProducto, PrecioDom) values (?,?,?,?,?)");
                enunciado.setInt(1,Integer.parseInt(txtid.getText()));
                enunciado.setString(2,txtnombre.getText());
                enunciado.setFloat(3, Float.parseFloat(txtprecio.getText()));
                enunciado.setString(4, cmbTipo.getSelectedItem().toString());
                enunciado.setFloat(5, Float.parseFloat(txtprecioDom.getText()));
                resul = enunciado.executeUpdate();
                if(resul <= 0 ){               
                    showMessageDialog(null,"Ocurrio un problema al guardar","Error",ERROR_MESSAGE);
                    return;
                }
                vista2();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }                
        }catch(AlitasException e){
            
            showMessageDialog(null,e.getMessage(),"Error",ERROR_MESSAGE);
        }    
    }
    public void actualizar()
    {        
        try{
            enunciado = conexion.prepareStatement("update  Productos set Nombre=?,Precio=?, PrecioDom=? where idProducto=? ");
            enunciado.setString(1,txtnombre.getText());
            enunciado.setFloat(2,Float.parseFloat(txtprecio.getText()));
            enunciado.setFloat(3,Float.parseFloat(txtprecioDom.getText()));
            enunciado.setInt(4,Integer.parseInt(txtid.getText()));
            int resul = enunciado.executeUpdate();
        }catch(Exception e){
            e.printStackTrace();
        }//
    }
    
  
    private void btncanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanActionPerformed
       vista2();
    }//GEN-LAST:event_btncanActionPerformed

    private void btnagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagActionPerformed
        agregar();            
    }//GEN-LAST:event_btnagActionPerformed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("Recursos/icono.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarProductos().setVisible(true);
            }
        });
    }
    DefaultTableModel dtm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnact;
    private javax.swing.JButton btnag;
    private javax.swing.JButton btncan;
    private javax.swing.JButton btneli;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproductos;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprecioDom;
    // End of variables declaration//GEN-END:variables
}
