
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salva
 */
public class Clientes extends javax.swing.JFrame {
    private ResultSet resultado;
   private PreparedStatement enunciado;
   private Connection conexion;
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        conectar();
        dtm= (DefaultTableModel) tblclientes.getModel();
      dtm.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtfiltro = new javax.swing.JTextField();
        cmbfiltro = new javax.swing.JComboBox<>();
        btnfiltrar = new javax.swing.JButton();
        btnvertodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtfiltro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbfiltro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbfiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Cliente", "Nombre" }));

        btnfiltrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnfiltrar.setText("Aceptar");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        btnvertodos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnvertodos.setText("Ver Todos");
        btnvertodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvertodosActionPerformed(evt);
            }
        });

        tblclientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Monto", "Visitas", "Calle", "Entre calles", "Descripcion", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblclientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnfiltrar)
                        .addGap(358, 358, 358)
                        .addComponent(btnvertodos)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfiltrar)
                    .addComponent(btnvertodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvertodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvertodosActionPerformed
        verclientes();
    }//GEN-LAST:event_btnvertodosActionPerformed

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        int c=cmbfiltro.getSelectedIndex();
        if(c==0)
        {
            
            try
            {
               Integer.parseInt(txtfiltro.getText());
            }catch(NumberFormatException ex)
                    {
                     showMessageDialog(null,"Id no valido.");   
                     return;
                    
                    }
        }
        switch(c)
        {
            case 0:verclientes(Integer.parseInt(txtfiltro.getText())); break;  
             case 1:verclientes(txtfiltro.getText()); break;  
        }
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void verclientes(String Nombre)
    {
        Object []O=new Object[8];   
        dtm.setNumRows(0);
        
        try{
           
        enunciado = conexion.prepareStatement("select * from Cliente,Domicilio where Cliente.idCliente=Cliente_idCliente and Cliente.Nombre like'"+Nombre+"%'");
        
         resultado = enunciado.executeQuery();
         while(resultado.next()){
            O[0]=resultado.getInt("idCliente");
            
             O[1]=resultado.getString("NombreCliente");
                     O[2]=resultado.getFloat("MontoGastado");
                     O[3]=resultado.getInt("Visitas");
                     O[4]=resultado.getString("Calle");
                     O[5]=resultado.getString("Callereferencia");
                     O[6]=resultado.getString("Descripcion");
                     O[7]=resultado.getString("Telefono");
                     dtm.addRow(O);
         }
         
      }catch(Exception e){
         e.printStackTrace();
      }
    }
    public void verclientes(int idcliente)
    {
        Object []O=new Object[8];   
        dtm.setNumRows(0);
        
        try{
           
        enunciado = conexion.prepareStatement("select * from Cliente,Domicilio where Cliente.idCliente=Cliente_idCliente and Cliente.idCliente="+idcliente+"");
        
         resultado = enunciado.executeQuery();
         while(resultado.next()){
            O[0]=resultado.getInt("idCliente");
            
             O[1]=resultado.getString("NombreCliente");
                     O[2]=resultado.getFloat("MontoGastado");
                     O[3]=resultado.getInt("Visitas");
                     O[4]=resultado.getString("Calle");
                     O[5]=resultado.getString("Callereferencia");
                     O[6]=resultado.getString("Descripcion");
                     O[7]=resultado.getString("Telefono");
                     dtm.addRow(O);
         }
         
      }catch(Exception e){
         e.printStackTrace();
      }
    }
    public void verclientes()
    {
        Object []O=new Object[8];   
        dtm.setNumRows(0);
        
        try{
           
        enunciado = conexion.prepareStatement("select * from Cliente,Domicilio where Cliente.idCliente=Cliente_idCliente ");
        
         resultado = enunciado.executeQuery();
         while(resultado.next()){
            O[0]=resultado.getInt("idCliente");
            
             O[1]=resultado.getString("NombreCliente");
                     O[2]=resultado.getFloat("MontoGastado");
                     O[3]=resultado.getInt("Visitas");
                     O[4]=resultado.getString("Calle");
                     O[5]=resultado.getString("Callereferencia");
                     O[6]=resultado.getString("Descripcion");
                     O[7]=resultado.getString("Telefono");
                     dtm.addRow(O);
         }
         
      }catch(Exception e){
         e.printStackTrace();
      }
    }
    
    ConexionBD con = new ConexionBD();
    
    private void conectar(){
        conexion = con.conectar();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("Recursos/icono.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }
DefaultTableModel dtm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton btnvertodos;
    private javax.swing.JComboBox<String> cmbfiltro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTextField txtfiltro;
    // End of variables declaration//GEN-END:variables
}
